# Generated by Django 2.1.5 on 2019-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sub_email',
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_contact',
            field=models.CharField(default='', max_length=50, verbose_name='被试联系方式'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_group',
            field=models.CharField(choices=[('0', 'admin'), ('1', '1组'), ('2', '2组'), ('3', '3组'), ('4', '4组')], default=1, max_length=1, verbose_name='被试组别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_number',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='被试学号'),
            preserve_default=False,
        ),
    ]
