# Generated by Django 2.1.5 on 2019-02-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='选项描述')),
                ('value', models.IntegerField(verbose_name='选项分值')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500, verbose_name='题目描述')),
                ('type_question', models.IntegerField(choices=[(1, '单选'), (2, '多选')], verbose_name='问题类型')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='问卷名称')),
                ('description', models.CharField(max_length=1000, verbose_name='问卷描述')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='email',
            field=models.CharField(default='email@example.com', max_length=50, verbose_name='被试邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='gender',
            field=models.IntegerField(default='1', verbose_name='被试性别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='age',
            field=models.IntegerField(verbose_name='被试年龄'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='date_created',
            field=models.DateTimeField(verbose_name='被试注册时间'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=20, verbose_name='被试姓名'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Survey', verbose_name='所属问卷'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Question', verbose_name='所属问题'),
        ),
        migrations.AddField(
            model_name='choice',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Option', verbose_name='回答'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Question', verbose_name='所属问题'),
        ),
        migrations.AddField(
            model_name='choice',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Subject', verbose_name='所属被试'),
        ),
    ]
