# Generated by Django 2.1.5 on 2019-02-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190225_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='gender',
            field=models.IntegerField(default=1, verbose_name='被试性别'),
        ),
    ]
