# Generated by Django 2.1.5 on 2019-03-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190225_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50, verbose_name='被试姓名')),
                ('store_stars', models.CharField(max_length=5, verbose_name='被试姓名')),
                ('store_avg', models.CharField(max_length=5, verbose_name='被试姓名')),
                ('store_addr', models.CharField(max_length=50, verbose_name='被试姓名')),
                ('store_num_review', models.IntegerField(verbose_name='被试年龄')),
                ('store_rec', models.CharField(max_length=50, verbose_name='被试姓名')),
                ('store_region', models.CharField(max_length=20, verbose_name='被试姓名')),
                ('store_category', models.CharField(max_length=20, verbose_name='被试姓名')),
                ('store_flavor', models.CharField(max_length=5, verbose_name='被试姓名')),
                ('store_envir', models.CharField(max_length=5, verbose_name='被试姓名')),
                ('store_service', models.CharField(max_length=5, verbose_name='被试姓名')),
                ('store_phone', models.CharField(max_length=30, verbose_name='被试姓名')),
            ],
        ),
    ]
