# Generated by Django 2.1.5 on 2019-03-18 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190319_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='选项描述')),
                ('value', models.IntegerField(verbose_name='选项分值')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500, verbose_name='题目描述')),
                ('type_question', models.IntegerField(default=1, verbose_name='问题类型')),
                ('order', models.FloatField(default=0, verbose_name='问题顺序')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='问卷名称')),
                ('description', models.CharField(max_length=1000, verbose_name='问卷描述')),
                ('category', models.IntegerField(default=1, verbose_name='问卷类别')),
                ('group', models.IntegerField(default=0, verbose_name='问卷组别')),
            ],
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='sur_sub',
        ),
        migrations.RemoveField(
            model_name='presurvey',
            name='sub_id',
        ),
        migrations.DeleteModel(
            name='PostSurvey',
        ),
        migrations.DeleteModel(
            name='PreSurvey',
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Survey', verbose_name='所属问卷'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Question', verbose_name='所属问题'),
        ),
        migrations.AddField(
            model_name='choice',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Option', verbose_name='回答'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Question', verbose_name='所属问题'),
        ),
        migrations.AddField(
            model_name='choice',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Subject', verbose_name='所属被试'),
        ),
    ]
