# Generated by Django 2.1.5 on 2019-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190319_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.CharField(default='该用户没有评价', max_length=500, verbose_name='点评内容'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.CharField(default='2019-01-01', max_length=100, verbose_name='点评日期'),
        ),
    ]
