# Generated by Django 2.1.5 on 2019-03-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190323_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_pic',
            field=models.URLField(default='', max_length=300, verbose_name='商户图片'),
        ),
    ]
