# Generated by Django 2.1.5 on 2019-03-31 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_store_store_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='日志时间')),
                ('action', models.CharField(max_length=50, verbose_name='行为')),
                ('value', models.CharField(max_length=50, verbose_name='值')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Subject', verbose_name='所属被试')),
            ],
        ),
    ]
